package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/kajidog/graphql-sse-test/apps/backend/graph/model"
	"github.com/kajidog/graphql-sse-test/apps/backend/middleware"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, nickname string) (*model.User, error) {
	return r.UserService.Login(nickname)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, content string) (*model.Message, error) {
	userID, ok := middleware.UserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized: user not logged in")
	}
	return r.MessageService.SendMessage(userID, content)
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context) ([]*model.Message, error) {
	return r.MessageService.GetMessages(), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := middleware.UserIDFromContext(ctx)
	if !ok {
		return nil, nil
	}
	user, _ := r.UserService.GetUser(userID)
	return user, nil
}

// MessageAdded is the resolver for the messageAdded field.
func (r *subscriptionResolver) MessageAdded(ctx context.Context) (<-chan *model.Message, error) {
	id := uuid.New().String()
	ch := r.MessageService.Subscribe(id)

	go func() {
		<-ctx.Done()
		r.MessageService.Unsubscribe(id)
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
